[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
solc_version = "0.8.26"
solc_version = "0.8.28"

auto_detect_solc = false
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "interfaces/=src/interfaces/",
    "libraries/=src/libraries/",
    "TitanV2/=src/interfaces/TitanV2/",
    "TitanV2/libraries/=src/libraries/TitanV2/"
]

